### PR TITLE
Some fixes improvements

### PR DESCRIPTION
**Pull request by lilydjwg**

### CODE REVIEW

**Comment by lilydjwg** [comment]
I choose `x` instead of `d` because `d` is a transitive verb, i.e. you can say `dj`, `d4l`, `dab`. But in this case the mapping will only delete an entry immediately, without a following object. You don't need to use `dd` to delete a line, you can't use `d2j` to delete three entries. `x` has the meaning to delete and doesn't need an object.

**Comment by ozra** [comment]
It's obviously thought through, well I just changed it locally :) It could be a setting though - since there seems to be differing mindsets as to which pops up in the head.

**Comment by lilydjwg** [comment]
Well, I've made both work so users can use whatever they prefer.

**Comment by ozra** [comment]
'd' works fine in my private patch - it's most likely because you have a compose-chain of keys beginning with a `d` in your specific configuration. Then vim has to wait to see if it receives more letters that can complete the longer map chains, before letting the single `d` act...

**Comment by jm3** [comment]
@yegappan, it would be nice to have this fix that @lilydjwg made for deleting files. anyway we could help test + get this merged?

**Comment by Arnie97** [comment]
@ozra  To make it more consistent with other parts of Vim, I mapped the command to `dd` in my own fork ;-) otherwise I would always delete two entries accidentally when I actually wanted to delete just one.

Well, still not ideal since commands like `3dd` or `d10G` won't work.

**Comment by yegappan** [comment]
Thanks for the patch. Most of the changes in this PR have been incorporated now.

**Comment by lilydjwg** [comment]
> Most of the changes in this PR have been incorporated now.

No, at least the important https://github.com/yegappan/mru/pull/11/commits/4c86f1159de5b23d61c04e7a2085333a7b1e2636 hasn't. This commit is important to preserve data in case like a system crash or power outage.

**Pull request closed without merging**
