### PR TITLE
Bugfix - <silent> key mappings prevent Vim from asking the user to enter the encryption key

### PR DESCRIPTION
**Pull request by jamescherti**
MRU/edit/view keyboard mappings: remove `<silent>` and replace `:call` with `<cmd>call`.

Reason: `<silent>` prevents Vim from asking the user _"Enter encryption key:"_ when an encrypted file is opened by MRU 
(`:help encryption`).

### CODE REVIEW

**Comment by yegappan** [comment]
The `<cmd>` feature is available only in recent versions of Vim.  The MRU plugin supports older Vim versions also. So this change cannot be made to the plugin.

**Comment by jamescherti** [comment]
This pull request fixes a bug (MRU key mappings prevent Vim from asking "Enter encryption key:" when an encrypted file is opened by MRU).

1. We could maintain backward compatibility by checking if <cmd> is supported.
2. Another solution is to remove `<silent>` (less interesting).

What do you think?

**Comment by yegappan** [comment]
Can you add a Vim version check for the `<cmd>` support? If it is available, then `<cmd>` can be used in the maps, otherwise the existing method for the maps can be used.

**Comment by jamescherti** [comment]
There is probably a way to check if `\<cmd>` is supported by Vim. I will do some research and come back to you, @yegappan .

**Comment by yegappan** [comment]
The support for `<cmd>` was added by patch 8.2.1978 (https://github.com/vim/vim/commit/957cf67d50516ba98716f59c9e1cb6412ec1535d).  You can check for this patch using `has('patch-8.2.1978')`.

**Comment by jamescherti** [comment]
Yes, @yegappan . I will use `has("patch-8.2.1978")` to check if Vim supports `<cmd>`.

**Comment by jamescherti** [comment]
I updated the Pull Request with the suggested changes. 

MRU key mappings will use `<cmd>` when `has('patch-8.2.1978')` returns a non-zero value. Otherwise, the key mappings will use `<silent>`.

**Comment by yegappan** [comment]
Test16 (which opens multiple files from the MRU window in normal and visual mode) is failing with this change.

**Comment by jamescherti** [comment]
It seems to be caused by the following key mappings, when `<cmd>` is supported by Vim:
```
  execute 'nnoremap <buffer> ' . l:silent . '<CR> ' .
        \ l:cmd . 'call <SID>MRU_Select_File_Cmd("edit,useopen")<CR>'
  execute 'vnoremap <buffer> ' . l:silent . '<CR> ' .
        \ l:cmd . 'call <SID>MRU_Select_File_Cmd("edit,useopen")<CR>'
```

I will investigate and get back to you.

**Comment by jamescherti** [comment]
I have fixed the issue in the latest commit. Now all unit tests pass.

**Comment by jamescherti** [comment]
Thank you for merging this pull request, @yegappan.

**Pull request merged**
